spring:
  datasource:
    url: jdbc:h2:file:./LunchVoter;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso

cache:
  scheduled-eviction:
    enabled: true
    cron: '@midnight'

logging:
  aspect:
    enabled: true

vote:
  decision-time: '11:00'